### ISSUE TITLE
Automatic French Removal

### ISSUE THREAD

**Issue by HughP** [HughP/dnj-corpus#24]
Need to automate the removal of French text.

**Comment by iandoug** [comment]
Going by my memory from when I manually deleted the text from the mass-text file, the section starts off the same, but does not always end the same.

If I was doing the text cleanup, I would have done it in one perl program, which would read in each file sequentially, (or the one consolidated first) and write out one file at the end.
Along the way, would apply whatever edits necessary to each line.

If doing this way, then you could have a loop which would look for the (consistent?) starting line, then skip all the lines until one of several ending lines (to be determined the hard way).

BTW the current corpus consolidated file is too big to test happily with KLA.... once the input file size starts getting over around 40 - 50 K the analysis process gets slow.

**Comment by iandoug** [comment]
This seems to work. Don't laugh at my coding style :-). Was trained in Pascal so do curly braces like Pascal BEGIN END.
[remove-french.zip](https://github.com/HughP/dnj-corpus/files/2094600/remove-french.zip)

**Comment by iandoug** [comment]
If you get different "patterns" of French then will need to update, but works with current corpus.

**Comment by iandoug** [comment]
Attached revised version of script dealing with one edge case, as well as resulting corpus and text removed.
[french-be-gone.zip](https://github.com/HughP/dnj-corpus/files/2114903/french-be-gone.zip)

Either in this process or another, I came across instances of hyphen-minus which need to be changed to tone character minus, I suspect.

**Comment by HughP** [comment]
I built my own using unix tools so that is now in the corpus.
