### ISSUE TITLE
Tone

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corpus#25]
Was trying to find The Big Dummy's Guide to Tone Usage in Dan, only found one of your readmes.

Seems like they only use three markers, high, medium and low.

Can we re-invent the wheel and use some of these instead of the confusing = ' and , ?

Tone letters
--
02E5 | ˥ | Modifier Letter Extra-High Tone Bar
02E6 | ˦ | Modifier Letter High Tone Bar
02E7 | ˧ | Modifier Letter Mid Tone Bar
02E8 | ˨ | Modifier Letter Low Tone Bar
02E9 | ˩ | Modifier Letter Extra-Low Tone Bar

**Comment by HughP** [comment]
Reinventing is not part of the options.

I'll work on describing tone after dinner in Eugene UTC/GMT -7:00 hours.
The before and after pair together with null to create patterns. :-)

**Comment by HughP** [comment]
The best place to find the patters is in the Readme.md which describes the writing system.
