### ISSUE TITLE
Spaces

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corpus#29]
Um, in things like
bhaʼgü.꞊Dhusi

Should there be a space after the period? Or is this all actually one word?

**Comment by HughP** [comment]
There should be spaces. I've got a `grep` that I can use to look for these
and insert spaces.

**Comment by iandoug** [comment]
I guess =Wegine - -dhöökpö
should become 
=Wegine- -dhöökpö

but -Dukwitaa - ’ka
 I don't know ... can't see any cases of -’ which then means
-Dukwitaa- ’ka
but no other uses of -Dukwitaa-  either ...

Any ideas?

**Comment by HughP** [comment]
> -Dukwitaa- ’ka

That looks right to me.

**Comment by HughP** [comment]
I think I cleaned this up and solved it in the most recent version of the `.bash` script.
