### ISSUE TITLE
Language design

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corpus#31]
Just an observation... :-)

Given:

U+0020 | 71305 | Space
U+02D7 | 30723 | Modifier Letter Minus Sign
U+0061 | 27938 | Latin Small Letter A
U+02BC | 19756 | Modifier Letter Apostrophe

where just about every word uses 2D7, one would think that they should make that tone the default, and mark the other tones only ... (if space on each side of word, and 2D7 is almost half the number of spaces...)

**Comment by HughP** [comment]
One would think....

**Comment by iandoug** [comment]
And not just people, but the experts too :-)

![screenshot_20180624_203657](https://user-images.githubusercontent.com/12673886/41822366-af3784e4-77ee-11e8-8248-05066c60e049.png)

**Comment by HughP** [comment]
Where is that quote from?

**Comment by HughP** [comment]
Got it: https://halshs.archives-ouvertes.fr/halshs-01287458/document

**Comment by iandoug** [comment]
I found it in Google Books, but a quick scan through shows your source similar/identical ... guess it was published in more than one place.
http://tinyurl.com/y9okg59x

Author has written several pertinent books/articles.

Was actually trying to find a word list / dictionary, so far without success.
Wanted to see if any words begin with hook v, in case those in the corpus are actually typos.
