### ISSUE TITLE
Random brackets

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corpus#33]
Hi
I guess the bracket in the last line should be a tone mark, other instances of the word mostly use word-minus or nothing. Editor does not find matching closing bracket.

ʼYö ʼwo˗ dhɛɛˮ kpɔ ʼwo˗ pö: «ʼYö ʼsɔng˗ ˗më ʼö ʼü˗ ˮyɩɩ to ?»  ʼyö˗ ˗yɔɔ bɔ
ʼö˗ pö: «Dhiang ʼö sënnë ʼdhö kë˗ zë ꞊diö bha ˗yö n ʼgü ˮyɩɩ ˮyɩɩ ˗sü
˗dedewo.»  (Mɛ ʼgbɛ ˗dhɛ ˗wo ꞊dhɛ ʼsɔng˗ ʼdhö.

**Comment by nqthqn** [comment]
Does the [README.md](https://github.com/HughP/dnj-corpus/blob/master/README.md) tangentially addresses this?

> The use of French style quote marks 〈«〉, 〈»〉 is confusing to Dan authors. That is, opening and closing quote marks appear to be used interchangeably in opening quotations. Additionally, there are quite a few cases where closing quote marks are missing. If software engineers for grammar and spelling checkers can manage, adding a function which checks for closing quote marks (of any kind), much like is done for programmers in IDEs, would benefit many new writers of minority languages.

**Comment by HughP** [comment]
Per haps this should be a tone mark, as that does seem to be the logical
place for one. But I am not sure which one.

**Comment by iandoug** [comment]
I was going to just fix that one but I see there are actually quite a lot of unbalanced brackets, and putting in a regex to fix each one (using the notorious SWAG method) is probably not the best way.
Will ponder it a bit. See the red bits in attached.

![screenshot_20180623_003349](https://user-images.githubusercontent.com/12673886/41802076-b3f56bfc-767e-11e8-870d-00e12e69a162.png)

**Comment by HughP** [comment]
Wow this is the first time seeing that screen shot... great way to visualize this across the whole corpus.
