### ISSUE TITLE
Capital hook-v with diaeresis

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corpus#36]
Hi

I can't actually find any capital hook V with diaeresis Ʋ̈ in the corpus.

Does it exist in real life? If not, then the range of viable fonts suddenly got a bit bigger...

**Comment by iandoug** [comment]
The wordcount from the corpus says:
ʋ  1
ʋʋ  22
ʋ̈  2
ʋ̈klʋ̈  1

Which I suppose in theory means a word COULD start with the capital. Then there is the use-case for headlines etc where everything is in capitals... what they sometimes do here in Afrikaans (whether for aesthetic  reasons or lack of glyph in font, I don't know), but I've seen things like VANWEë  in stead of VANWEË in newspaper billboards etc.

**Comment by HughP** [comment]
Typographic Tradition does make a difference. The Germans showed us with `ß` that even if the only reason for having a upper-lower case pair is because we need to use all CAPS for some typographical layout - we still need the case paring.
